name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering as well

jobs:
  add_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "bot@github.com"

      - name: Check for Changes
        id: check_changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes detected."
            exit 0
          fi

      - name: Commit and Push Changes
        if: success()
        run: |
          git add .
          git commit -m "Daily commit: $(date)"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
